export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const CREATE_COMMENT_START = "CREATE_COMMNET_START";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMNET_SUCCESS";

export const CLEAR_ERROR = "CLEAR_ERROR";